version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data